<?php

$class = '\DateTime';

$myClass = 'WebimpressCodingStandardTest\Ruleset';

$interface = '\Traversable';
$lowercase = '\traversable';

$trait = 'WebimpressCodingStandard\Helper\NamespacesTrait';

$nonExistingClass = 'MyNamespace\ClassDoesNotExist';
$nonSlash = 'DateTime';

$doubleNamespaceSeparator = 'WebimpressCodingStandardTest\\Ruleset';
$fourBackslashes = 'WebimpressCodingStandardTest\\\\Ruleset';
$spaceInTheName = 'WebimpressCodingStandardTest Ruleset';
$newLineInTheName = 'WebimpressCodingStandardTest
    Ruleset';

$spaceAtTheBeginning = ' WebimpressCodingStandardTest\\Ruleset';
$spaceAtTheEnd = ' WebimpressCodingStandardTest\\Ruleset ';

$namespaceSeparatorAtTheEnd = 'WebimpressCodingStandardTest\\Ruleset\\';
$justNamespaceSeparator = '\\';
