<?php

while (true) {
    switch (true) {
        case true:
            if ($x) {
                continue;
            } elseif ($y) {
                continue;
            } else {
                continue;
            }
            continue;
        case false:
            continue;
        case null:
            if ($x) {
                continue 2;
            } elseif ($y) {
                continue 2;
            } else {
                continue 2;
            }
            continue 2;
    }
}
