<?php

!!$var;

! ! $var;

(binary)$var;
(boolean)$var;
(integer)$var;
(object)$var;
(array)$var;
(int)$var;
(bool)$var;
(string)$var;
(double)$var;
(float)$var;
(real)$var;
(unset)$var;

(binary)   $var;
(boolean)  $var;
(integer)  $var;
(object)   $var;
(array)    $var;
(int)      $var;
(bool)     $var;
(string)   $var;
(double)   $var;
(float)    $var;
(real)     $var;
(unset)    $var;

( boolean ) $var;
(boolean ) $var;
(   boolean) $var;

( integer )$var;
(integer )$var;
(  integer)$var;

(BINARY)   $var;
(BOOLEAN)  $var;
(INTEGER)  $var;
(OBJECT)   $var;
(ARRAY)    $var;
(INT)      $var;
(BOOL)     $var;
(STRING)   $var;
(DOUBLE)   $var;
(FLOAT)    $var;
(REAL)     $var;
(UNSET)    $var;

$binary = b'0x123';
