name: Unit Tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        dependencies: ['lowest', 'latest']
        php-versions: ['7.3', '7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php-versions }}, ${{ matrix.dependencies }} dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        env:
          DEPS: ${{ matrix.dependencies }}
        run: |
          if [[ $DEPS != 'lowest' ]]; then composer update --no-progress  --prefer-dist --optimize-autoloader ; else composer update --no-progress --prefer-lowest  --prefer-stable --optimize-autoloader ; fi

      - name: Run tests
        run: composer test
